version: '3.8'

services:
  whatsapp-auto-warmer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-auto-warmer
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
      - ./.wwebjs_auth:/usr/src/app/.wwebjs_auth
      - ./.wwebjs_cache:/usr/src/app/.wwebjs_cache
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Add any other environment variables your app needs